name: GDG Toledo
description: Que no te lo cuente tu cuñado en la cena de navidad
meta_description: "GDG Toledo"
domain_name: 'https://javierlopezdeancos.github.io'

aboutPage: false

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20

collections:
  members:
  meetups:

google_analytics: 'UA-XXXXXXXX-X'

disqus: true
disqus_shortname: 'GDGToledo'

# Details for the RSS feed generator
url:            'https://javierlopezdeancos.github.io'
author:         'GDG Toledo'
authorTwitter:  'GDGToledo_es'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages

        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
