baseurl: '/web'
name: 'GDG Toledo'
description: 'El espíritu de este grupo es fomentar y compartir las buenas prácticas y las experiencias en herramientas, frameworks, lenguajes, etc'
meta_description: 'GDG Toledo'
domain_name: 'https://gdgtoledo.github.io'

aboutPage: false
destination: docs

markdown: 'kramdown'
highlighter: 'rouge'

plugins:
  - 'jekyll-paginate-v2'

pagination:
  enabled: true
  per_page: 10
  permalink: '/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

collections:
  members:
    output: true
    permalink: '/members/:path/'
  meetups:
    output: true
    permalink: '/meetups/:path/'
  posts:
    output: true
    permalink: '/posts/:path/'

autopages:
  enabled: true
  collections:
    enabled: true
    slugify:
      mode: 'ascii'
      cased: true

navigation:
  - url: /
    title: 'home'
    weight: 1

  - url: '/meetups'
    title: 'meetups'
    weight: 2

  - url: '/posts'
    title: 'posts'
    weight: 3

  - url: '/credits'
    title: 'credits'
    weight: 3

google_analytics: 'UA-XXXXXXXX-X'

disqus: true
disqus_shortname: 'GDGToledo'

# Details for the RSS feed generator
url: 'https://gdgtoledo.github.io/web'
author: 'GDG Toledo'
authorTwitter: 'GDGToledo_es'
timezone: Europe/Madrid

permalink: '/:year/:title/'
